### ISSUE TITLE
GPT Improvement

### ISSUE THREAD

**Issue by franklegolasyoung** [sglkc/waifu-otw#3]
Hi. Thanks for your effort of this great project. The openai got the gpt-3.5-turbo api. Is there any plans for you to apply this new feature into this project to make the response more lively?

**Comment by sglkc** [comment]
Appreciate the comment 😄

I do have plans and it's always on my to-do list, but I don't think I'll update this project anymore and instead make a new repository with the GPT integration.

One of the points of this project is to make a fully client-sided AI, so using APIs is a no-no.

However, you can fork this repository and make your own modifications as you like ☝️

**Comment by franklegolasyoung** [comment]
Thanks for your reply! Hope to see the new project soon!
